#!/usr/bin/env python

import climate
import illuminatus
import illuminatus.commands

climate.add_arg('--db', default='photo.db', help='connect to this database')

cmd = climate.add_command('help')
cmd.set_defaults(mod='help')


def main(args):
    if getattr(args, 'mod', 'help') == 'help':
        climate.usage()
        return
    illuminatus.db.init(args.db)
    args.mod.main(args)


if __name__ == '__main__':
    climate.call(main)
