#!/usr/bin/env python

import climate
import illuminatus
import illuminatus.commands
import logging
import os

climate.add_arg('--db', help='connect to this database')

cmd = climate.add_command('help')
cmd.set_defaults(mod='help')


def main(args):
    if getattr(args, 'mod', 'help') == 'help':
        climate.print_help()
        return
    db = args.db or os.environ.get('ILLUMINATUS_DB')
    if not db:
        logging.error('no database specified!')
        climate.print_help()
        return
    illuminatus.db.init(db)
    args.mod.main(args)


if __name__ == '__main__':
    climate.call(main)
