#!/usr/bin/env python

import lmj.cli
import lmj.photos.commands
import os

lmj.cli.add_arg('--db', default='photo.db', help='connect to this database')


def main(args):
    args.mod.main(args)


if __name__ == '__main__':
    lmj.cli.call(main)
