#!/usr/bin/env python

import climate
import lmj.media
import lmj.media.commands

climate.add_arg('--db', default='photo.db', help='connect to this database')


def main(args):
    lmj.media.db.init(args.db)
    args.mod.main(args)


if __name__ == '__main__':
    climate.call(main)
